# Generated by Django 2.0.1 on 2018-02-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTwo', '0006_auto_20180209_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimate',
            old_name='crew_list',
            new_name='contaminants',
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='current_treatmant',
            new_name='treatmant_plan',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='date_opened',
        ),
        migrations.AddField(
            model_name='site',
            name='client_name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
